### ISSUE TITLE
Custom prefix for relative-time

### ISSUE THREAD

**Issue by tomas-mikula** [github/relative-time-element#102]
I noticed that for `<relative-time>` which is further than 1 month ago we show example: `on 14 April 2018`

Would it be possible to add custom prefix, which if not specified would default to `on` (for backwards compatibility) but in case I could specify empty string so I would get just `14 April 2018`?

**Comment by keithamus** [comment]
This is now possible with the `prefix` attribute, which defaults to `'on'` but can be set to `''` to remove the prefix.
