### ISSUE TITLE
Bug displaying 'in 3 hours'

### ISSUE THREAD

**Issue by Pau1fitz** [github/relative-time-element#126]
Looks like there could be a bug here, if you are using this library on the  Github `User Feed Page`.

I believe this should be `3 hours ago`, as opposed to `in 3 hours` unless github is predicting the future.

<img width="100" alt="Mind blown" src="https://media2.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif?cid=790b76118dfbf6c6749f1d44d8178b289e7f1231acfc7352&rid=giphy.gif">

see screenshot below:

<img width="493" alt="Screenshot 2019-08-28 at 13 51 10" src="https://user-images.githubusercontent.com/6873736/63857049-e83d7880-c99a-11e9-8260-cd96f99f1773.png">

**Comment by koddsson** [comment]
This is probably due to either server time-sync issues or client time settings. Can you reproduce this consistently?

**Comment by Pau1fitz** [comment]
@koddsson will have to wait for someone to star one of my repos again 😁

**Comment by koddsson** [comment]
@Pau1fitz Can't you just go to the homepage (https://github.com/) and see any of the activity in the list there?

**Comment by Pau1fitz** [comment]
That is the page I have gone to but the latest star is from 12 hours ago
<img width="500" alt="Screenshot 2019-08-29 at 13 31 32" src="https://user-images.githubusercontent.com/6873736/63940425-58163680-ca61-11e9-9f24-b946ea8cb5f6.png">
