### ISSUE TITLE
Suggestion: improve date tooltip discoverability

### ISSUE THREAD

**Issue by floooh** [github/relative-time-element#141]
See this twitter thread:

https://twitter.com/FlohOfWoe/status/1325427548650532864

Currently it's easy to miss the mouse-hover tooltip with the absolute time, especially in strings like this:

![image](https://user-images.githubusercontent.com/1699414/98466705-92d13e00-21d1-11eb-891c-71a8e99ec2e0.png)

The relative time "29 days ago" is fairly useless, it would be better to know the absolute date, which is hidden in a tooltip which is easy to miss (the date sub-string doesn't make it obvious that something will happen on mouse-hover, and the delay until the tooltip appears is way too long to discover it "by accident").

A visual clue like the dashed line here would do wonders for discoverability:

![EmTicPUWEAENOwM](https://user-images.githubusercontent.com/1699414/98466785-06734b00-21d2-11eb-8ce2-b1a4e9cb8c3e.png)

**Comment by joelhawksley** [comment]
@flooh thank you for the suggestion! I've filed this issue for our design team to look into.

**Comment by keithamus** [comment]
I'm going to close this as this issue tracker should be related to issues around the implementation of `relative-time`, not its use on GitHub.com. Of course if you're still finding this to be an issue please do contact `support@github.com`!
