### ISSUE TITLE
With relative times, tooltip shows in browser language instead of document language

### ISSUE THREAD

**Issue by JasonBarnabe** [github/relative-time-element#143]
When using relative times, times older than a month are show absolutely, localized using the document's language (good!); however, the `title` is localized using the browser language (bad!). This should consistently use the document language.

https://github.com/github/time-elements/blob/4414cbacdb1e0cf95b7e99960897bb0c55736323/src/extended-time-element.ts#L64

**Comment by Wulfheart** [comment]
@JasonBarnabe did you open a PR?

**Comment by keithamus** [comment]
In `v3.2.0` they both now use the same way to determine the local; looking for the closest element with a `lang` attribute. So I believe this fixes the issue. Let me know if you run into any other issues.
