### ISSUE TITLE
Add better jsx support

### ISSUE THREAD

**Issue by Quazie** [github/relative-time-element#163]
Properly add the various elements to the JSX intrinsic space similar to:

```type CustomElement<T> = Partial<T & DOMAttributes<T> & { children: any }>;

declare global {
  namespace JSX {
    interface IntrinsicElements {
      ["time-ago"]: CustomElement<TimeAgoElement>;
    }
  }
}```

**Comment by keithamus** [comment]
@Quazie we looked into this but ultimately I don't think there is a tenable solution:

> Experimenting with this a bit, this is untenable. React requires a type that includes references to the React library itself, which we're not prepared to bring into this custom element.
> 
> ```ts
> declare global {
>   namespace JSX {
>     interface IntrinsicElements {
>       'relative-time': React.DetailedHTMLProps<React.HTMLAttributes<RelativeTimeElement>, RelativeTimeElement>
>     }
>   }
> }
> ```
> 
> This should be defined in consuming libraries if they want to use this in React.


I'll close this out as I don't think we can reasonably support this.
