### ISSUE TITLE
datetime without weekday

### ISSUE THREAD

**Issue by allanegidio** [github/relative-time-element#236]
Hello.

I've been having some problems to remove weekday after update to version 4.1.2 when format is datetime but I couldn't find a way. 
I saw an example without weekday but i was not able to reproduce. 
Someone knows how to do that?
![image](https://user-images.githubusercontent.com/12875691/208157690-52dc417d-8a5d-46fc-b195-9a29ef98be0a.png)

**Comment by keithamus** [comment]
Thanks @allanegidio for the issue.

It should be possible by setting `weekday=""` (as in an empty value).

**Comment by keithamus** [comment]
Looks like it wasn't possible due to a bug in the logic. It's now possible in 4.1.4!
