### ISSUE TITLE
Package no longer publishing to NPM?

### ISSUE THREAD

**Issue by birdcar** [github/relative-time-element#238]
Hi there! 👋🏽 

It seems that somehow, despite [the `publish to npm` action succeeding](https://github.com/github/relative-time-element/actions/runs/3716465510/jobs/6302824978) the package has not been updating on NPM since v4.0.0:

https://www.npmjs.com/package/@github/time-elements?activeTab=versions

I'm currently running into a minor bug that was fixed in #219 (and therefore the fix is in the v4.1.5 release), but since npm only has 4.0.0 available I'm stuck.

Are there plans to resolve the discrepancy and ensure that the latest version of the package is available via npm?

**Comment by keithamus** [comment]
Hey @birdcar thanks for the issue!

We've renamed the package, so it's now published under `@github/relative-time-element`. Changing your install to point to that package name instead should give you the latest version.

I'll be sure to deprecate the old package name in the new year.

**Comment by birdcar** [comment]
@keithamus gotcha! I'll update our package json and make sure we consume it correctly.

A depreciation notice would definitely be appreciated 🙏

Thank you!

**Comment by keithamus** [comment]
https://www.npmjs.com/package/@github/time-elements marked as deprecated.
