### ISSUE TITLE
Wrong human text

### ISSUE THREAD

**Issue by antonio-fr** [github/relative-time-element#250]
I'm supposing this is the code that writes dates on Github web front.

1 year ago, it writes "2 years ago"
![image](https://user-images.githubusercontent.com/7551901/218257183-7b754dba-4614-4af8-a8a4-ce9a3bb9277e.png)

**Comment by turbo** [comment]
Same issue on https://github.com/grayjoking/backhand (flagged up by user):

![image](https://user-images.githubusercontent.com/8023543/218694495-b1ab2700-c87b-458b-8d18-735e4f2832f0.png)

**Comment by stapelberg** [comment]
Here’s a test case that illustrates the issue:

```diff
--- a/test/relative-time.js
+++ b/test/relative-time.js
@@ -2411,18 +2411,18 @@ suite('relative-time', function () {
         expected: 'in 3 years',
       },
       {
-        reference: '2022-12-31T12:00:00.000Z',
-        datetime: '2024-03-01T12:00:00.000Z',
-        tense: 'future',
-        format: 'micro',
-        expected: '3y',
+        reference: '2023-02-18T19:00:00.000Z',
+        datetime: '2021-02-02T20:49:31.000Z',
+        tense: 'past',
+        format: 'auto',
+        expected: '2 years ago',
       },
       {
-        reference: '2021-04-24T12:00:00.000Z',
-        datetime: '2023-02-01T12:00:00.000Z',
-        tense: 'future',
-        format: 'micro',
-        expected: '2y',
+        reference: '2023-02-18T19:00:00.000Z',
+        datetime: '2021-01-23T09:28:06.000Z',
+        tense: 'past',
+        format: 'auto',
+        expected: '2 years ago',
       },
     ])
```

Output:
```
test/relative-time.js:

 ❌ relative-time > legacy formats > <relative-time datetime="2021-02-02T20:49:31.000Z" tense="past" format="auto"  > => 2 years ago
      AssertionError: expected '3 years ago' to equal '2 years ago'
      + expected - actual
      
      -3 years ago
      +2 years ago
```

Might be related to https://github.com/github/relative-time-element/pull/249? cc @keithamus

**Comment by keithamus** [comment]
I have a refactor PR that’ll be ready soon which will resolve these without regressing the other cases we’ve run into.

**Comment by Wulfheart** [comment]
@keithamus currently I am trying to dive into the code. Could you please point me to the PR Seith the refactoring?

**Comment by keithamus** [comment]
I did some work on trying to create a polyfill for Temporal Durations so we could move to those but the work stalled due to the complexity of the Temporal APIs. I don't have an active branch or PR so the current code is the latest iteration.

**Comment by leduyquang753** [comment]
The bug is still present as of 1 Dec 2024. I have traced it down to the `roundToSingleUnit` function.

![image](https://github.com/user-attachments/assets/f330a0de-c8ee-4f72-8310-5fd022d01acf)

**Comment by wxiaoguang** [comment]
The simplest fix could be like this:  Fix duration calculation #296 

Feel free to edit my PR directly.

**Comment by silverwind** [comment]
Can confirm this is fixed by https://github.com/github/relative-time-element/pull/296.

**Comment by keithamus** [comment]
Thanks for triaging this one too!
