### ISSUE TITLE
precision=day should return "today" instead of "now"

### ISSUE THREAD

**Issue by jyasskin** [github/relative-time-element#279]
https://jsfiddle.net/oabcw7mz/ has an example of trying to render (now - 23 hours) with a precision of days, which should show "today" but actually shows "now".

I think the fix will involve making `getRelativeTimeUnit` https://github.com/github/relative-time-element/blob/a0483cee69830a46e16c2bb8969b601988a4e8e3/src/duration.ts#L206-L218

return the `precision` unit for empty durations.

**Comment by keithamus** [comment]
Sounds like you have a good handle on the problem. Would you like to make a PR>
