### ISSUE TITLE
Display text wrong

### ISSUE THREAD

**Issue by Leo01234** [github/relative-time-element#288]
![](https://github.com/user-attachments/assets/acb2d079-8d78-470a-9e82-d3c1765816be)

It should be something like "1 month ago", but it writes "yesterday".

![](https://github.com/user-attachments/assets/52a15a8e-a440-4c76-82c4-498fe20d686f)

Edit:

I just notice #281, but it seems not fixed.

**Comment by keithamus** [comment]
Can you please make a PR with a failing test? We have a bunch of tests in a file that look like this:

https://github.com/github/relative-time-element/blob/15ca61e1992f39f242aa4de0b35c14ce76062990/test/relative-time.js#L1806-L1812

If you copy that object and add a new one right below it with the values tweaked to represent the expected output, and we can see if it fails. If it does fail we can look at a fix.

**Comment by aprendendofelipe** [comment]
It's not a problem with `relative-time-element`. GitHub is not using version 4.4.2 yet.

See https://github.com/primer/react/pull/4803
