### ISSUE TITLE
time-ago wrong calcul

### ISSUE THREAD

**Issue by pkolodziejczyk** [github/relative-time-element#46]
For current date 2015-02-23T00:00:00.000Z (like)

The following html :
<time is="time-ago" format="micro" datetime="1900-02-01T00:00:00.000Z">

Give this result : 
<time is="time-ago" format="micro" datetime="1900-02-01T00:00:00.000Z" title="Feb 1, 1900, 12:09 AM GMT+0:09:21">117y</time>

Or it's should give 115 or maybe 116 not 117 !

Note : for date 002-02-01T00:00:00.000Z It's even more obvious.

**Comment by keithamus** [comment]
If you'd like to try the new release I believe this issue is likely fixed. If not let me know and we can revisit it.
